---
abstract: 'Templating using pure Perl code'
author:
  - 'Wolfgang Kinkeldei <wolfgang@kinkeldei.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-ByCode
requires:
  Catalyst::Runtime: 5.80
  Devel::Declare: 0.005007
  FindBin: 1.49
  HTML::Entities: 1.35
  HTML::Tagset: 3.10
  List::Util: 1.21
  MIME::Base64: 3.07
  Moose: 1.0
  Test::Builder: 0.86
  Test::Builder::Tester: 1.18
  Test::Exception: 0.27
  Test::Harness: 3.14
  Test::More: 0.86
  UUID::Random: 0.04
  YAML: 0.68
  ok: 0
version: 0.22
